---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    config.spring.io/enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      config.spring.io/enabled: "true"
  template:
    metadata:
      labels:
        app: nginx
        config.spring.io/enabled: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    config.spring.io/enabled: "true"
spec:
  selector:
    app: nginx
    config.spring.io/enabled: "true"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80