server:
  port: 8761

spring:
  application:
    name: spring-cloud-k8s-eureka-controller
  main:
    web-application-type: none
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30      # heartbeats frequency to renew instance registration (default 30 seconds)
    lease-expiration-duration-in-seconds: 40   # server to wait this long for a client heartbeat before removing it


logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    io.fabric8.kubernetes.client.informers.cache: OFF

k8s:
  informer:
    watcher-interval: 30
    label-enabled: config.spring.io/enabled
    label-register: condfig.spring.io/register
    primary-port-name: primary_port
