---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: springcloud

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: springcloud-eureka-controller
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: springcloud-eureka-controller
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: springcloud-eureka-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: springcloud-eureka-controller
subjects:
  - kind: ServiceAccount
    name: springcloud-eureka-controller
    namespace: default

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: eureka-server
    version: 0.0.1-SNAPSHOT
  name: eureka-server
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8761
  selector:
    name: eureka-server
    version: 0.0.1-SNAPSHOT
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: eureka-server
    version: 0.0.1-SNAPSHOT
  name: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eureka-server
      version: '0.0.1-SNAPSHOT'
  template:
    metadata:
      labels:
        name: eureka-server
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - name: eureka-server
          image: haybu/eureka-server:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MANAGEMENT_ENPOINTS_WEB_EXPOSURE_INCLUDE
              value: info,health,env
          ports:
            - containerPort: 8761
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 4
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  name: springcloud-eureka-controller
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8181
  selector:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  name: springcloud-eureka-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: springcloud-eureka-controller
      version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        name: springcloud-eureka-controller
        version: 0.0.1-SNAPSHOT
    spec:
      serviceAccountName: springcloud-eureka-controller
      containers:
        - name: springcloud-eureka-controller
          image: haybu/spring-cloud-k8s-eureka-controller:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8181
              name: http
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: EUREKA_SERVICE_URL_DEFAULT_ZONE
              value: "http://eureka-server.default.svc.cluster.local/eureka/"
            - name: MANAGEMENT_ENPOINTS_WEB_EXPOSURE_INCLUDE
              value: info,health,env
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5m
            limits:
              memory: 2Gi

