---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  name: springcloud-eureka-controller
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8181
  selector:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springcloud-eureka-controller
    version: 0.0.1-SNAPSHOT
  name: springcloud-eureka-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: springcloud-eureka-controller
      version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        name: springcloud-eureka-controller
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
      - name: springcloud-eureka-controller
        image: haybu/spring-cloud-k8s-eureka-controller:v7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8181
            name: http
            protocol: TCP
        env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
          - name: EUREKA_SERVICE_URL_DEFAULT_ZONE
            value: "http://eureka-server.default.svc.cluster.local/eureka/"
          - name: MANAGEMENT_ENPOINTS_WEB_EXPOSURE_INCLUDE
            value: info,health,env
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5m
          limits:
            memory: 2Gi
      serviceAccountName: springcloud-eureka-controller
#        livenessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /actuator/health
#            port: 8181
#            scheme: HTTP
#          initialDelaySeconds: 0
#          periodSeconds: 30
#          successThreshold: 1
#          timeoutSeconds: 10
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /actuator/health
#            port: 8181
#            scheme: HTTP
#          initialDelaySeconds: 0
#          periodSeconds: 4
#          successThreshold: 1
#          timeoutSeconds: 10
